# fly.toml app configuration file generated for gdrestore on 2023-11-15T17:09:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gdrestore"
primary_region = "ewr"

[build]
  image = "kinznzl/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51O4rO1BVWuXEBDdYUbIkJ4yTRIyiQElUL5yB6e8igs3FKAd2WpVnYpdVHjLFR1DE9hjBdkKyO0yVfKWOMq61K7UW00PfiQxAHr"
  Cloudinary__CloudName="dzowo24he"
  Cloudinary__ApiKey="959642637157445"

[experimental]
  allowed_public_ports = []
  auto_rollback = true  

[http_service]
  http_checks = []
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

